sandpack-react/src/common/Layout.tsx
sandpack-react/src/contexts/theme-context.tsx
sandpack-react/src/presets/Sandpack.stories.tsx
sandpack-react/src/presets/Sandpack.tsx
sandpack-react/src/presets/SandpackRunner.stories.tsx
sandpack-react/src/presets/SandpackRunner.tsx
sandpack-react/src/themes/index.ts
sandpack-react/src/types.ts
sandpack-react/src/utils/dom-utils.ts

Setting intial theme using user preference

---

sandpack-client/README.md

Added Docs for self hosting the bundler

---

sandpack-react/src/common/PrismHighlight.tsx
sandpack-react/src/components/CodeEditor/index.tsx
sandpack-react/src/components/CodeViewer/index.tsx
sandpack-react/src/components/FileExplorer/Directory.tsx
sandpack-react/src/components/Preview/index.tsx
sandpack-react/src/components/TranspiledCode/index.tsx

https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx

chore: use ternaries instead of `&&` in JSX

---

.gitignore
package.json
sandpack-playground/.env.example
sandpack-playground/package.json
sandpack-playground/src/App.tsx
sandpack-playground/src/index.html
sandpack-playground/src/index.tsx
sandpack-playground/start.js
yarn.lock

I've added a package that is very useful for debugging bundler issues without having to start storybook (which is fairly heavy and slow)
The only thing that really remains to make this the perfect debug tool is having a way to provide a sandbox id and loading that sandbox instead of hardcoding file content. Not entirely sure yet how that would work, might look into that after fixing some issues with the cat example

Sandpack Playground

---

sandpack-react/src/contexts/sandpackContext.tsx

fix: intersection observer threshold

---

sandpack-react/package.json
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/hooks/useCodeSandboxLink.ts
sandpack-react/src/presets/SandpackRunner.stories.tsx
sandpack-react/src/types.ts
yarn.lock

Waiting on codesandbox-import-utils latest to be published

WIP: passing environment next to the files

---

sandpack-react/src/templates/angular.ts
sandpack-react/src/templates/index.tsx
sandpack-react/src/templates/vue3.ts
sandpack-react/src/types.ts

Hi, @alexnm, there is the template code for angular and vue3, and I have test it in my own project~ Although as what you have mentioned in https://github.com/codesandbox/sandpack/issues/52, hope you can consider to merge this Pull Request and publish a patch version ~ thank you so much, cheers~

increase templates angular & vue3

---

.eslintrc
.husky/pre-commit
package.json
sandpack-client/src/types.ts
sandpack-react/src/common/LoadingOverlay.tsx
sandpack-react/src/components/Navigator/Navigator.stories.tsx
sandpack-react/src/components/Navigator/index.tsx
sandpack-react/src/components/Preview/Preview.stories.tsx
sandpack-react/src/components/Preview/RefreshButton.tsx
sandpack-react/src/components/Preview/index.tsx
sandpack-react/src/components/TranspiledCode/index.tsx
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/hooks/useLoadingOverlayState.ts
sandpack-react/src/hooks/useSandpack.ts
sandpack-react/src/hooks/useSandpackNavigation.ts
sandpack-react/src/presets/CustomSandpack.stories.tsx
sandpack-react/src/presets/Sandpack.stories.tsx
sandpack-react/src/presets/Sandpack.tsx
sandpack-react/src/templates/angular.ts
sandpack-react/src/templates/index.tsx
sandpack-react/src/templates/vue3.ts
sandpack-react/src/types.ts

WIP: Release 0.1

---

sandpack-react/src/presets/Theme.stories.tsx

feat(react): add dynamically stories for each theme

---

website/landing/components/Users/Users.tsx
website/landing/styles/globalStyles.ts

Refine the users section in the landing page.
- Fixes size of user's logos;
- Adjusts base font size;
1. 375px
2. 768px
3. 1440px
4. 1920px

feat(landing): refine users

---

.codesandbox/devtools.json
website/landing/components/Banner/Banner.tsx
website/landing/components/Community/Community.tsx
website/landing/components/Features/Features.tsx
website/landing/components/Features/icons.tsx
website/landing/components/Hero/Hero.tsx
website/landing/components/Showcase/Showcase.tsx
website/landing/website.config.json

Misc adjustments from a paring session w/ @marcovincit.

fix: misc spacing

---

website/landing/components/Api/Api.tsx
website/landing/components/Banner/Banner.tsx
website/landing/components/Community/Community.tsx
website/landing/components/Features/Features.tsx
website/landing/components/Hero/Hero.tsx
website/landing/components/Intro/Intro.tsx
website/landing/components/Showcase/Showcase.tsx
website/landing/components/Users/Users.tsx
website/landing/pages/index.tsx
website/landing/website.config.json

- Adds base padding to all sections in order to prevent content from touching the screen's boundaries;
- Force line breaks with inline `<br />` tags; cc @marcovincit 
- Simplifies structure around `Features` section;
- Aligns content to center of screen;
1. Checked breakpoints;

fix(landing): sections padding + force content line break

---

website/landing/components/Features/icons.tsx
website/landing/components/Hero/Hero.tsx
website/landing/components/Intro/Intro.tsx
website/landing/components/common/SandpackPreview.tsx
website/landing/components/common/index.ts
website/landing/package.json
website/landing/pages/_app.tsx
yarn.lock

Replaces content landmarks w/ actual Sandpack on Hero and Intro sections.
1. 375px
2. 768px
3. 1440px
4. 1920px

feat: adds sandpack to landing

---

website/landing/components/Intro/Intro.tsx
website/landing/components/common/CodeBlock.tsx
website/landing/components/common/SandpackPreview.tsx
website/landing/styles/sandpackTheme.ts
website/landing/website.config.json

Style code snippets + previews with custom theme.
1. Checked breakpoints;

feat: custom sandpack theme

---

website/landing/components/Api/Api.tsx
website/landing/components/Banner/Banner.tsx
website/landing/components/Hero/Hero.tsx
website/landing/components/common/Clipboard.tsx
website/landing/components/common/Resources.tsx
website/landing/components/common/index.ts

Closes CSB-1782.
- Hover states for resources links;
- Feedback when copying to clipboard;
- Miscellaneous spacing adjustments;

fix(landing): ui feedbacks

---

website/landing/components/Features/Features.tsx
website/landing/components/Users/Users.tsx
website/landing/components/common/Card.tsx
website/landing/components/common/Section.tsx

- Adds a "small" variant to card;
It mainly updates the card's width and font sizing;
- Updates features to use shared section and card components;
- Animates the features section;
Preview: https://bngwm-3001.pitcher-staging.csb.dev/.
https://user-images.githubusercontent.com/24959348/142656282-540f2960-b698-4f78-b806-9a40a99c6cbf.mov
1. Verified breakpoints;

chore: landing - refine features section

---

website/landing/components/AdvancedUsage/AdvancedUsage.tsx
website/landing/components/Banner/Banner.tsx
website/landing/components/common/ParallaxLogo.tsx

- Replaces static logo with moving one;
- Updates parallax logo api and usage;
https://user-images.githubusercontent.com/24959348/142916475-2e22e4ef-f7cc-4588-8bf2-f7d8a8d91565.mov
1. Manual verification on breakpoints;

feat: landing - parallax logo in banner

---

website/landing/components/common/Card.tsx

- Updates `code` styling inside of card description;
|Previous|Current|
|:-:|:-:|
|![mb2c8-3001 pitcher-staging csb dev_](https://user-images.githubusercontent.com/24959348/142927874-0b3118cb-563a-428b-8545-b58e82a7494e.png)|![ql60d-3001 pitcher-staging csb dev_](https://user-images.githubusercontent.com/24959348/142927503-09817a78-172d-4d16-8ca1-d18237e2835c.png)|

feat: landing - update card description code snippets

---

website/landing/website.config.json

This PR is adding copy under the social links and for the showcase section.

refactor(landing): add social and showcase copy to the landing page

---

website/landing/components/Showcase/Showcase.tsx
website/landing/pages/index.tsx

- Updates showcase structure to use shared components;
- Adds "parallax" effect to showcase highlights;
This does not include the updated content.
https://user-images.githubusercontent.com/24959348/143378372-88d90c4e-1caf-4d36-9fba-a7eea2373bea.mov
1. Manual verification on supported breakpoints;

feat: landing - update showcase structure

---

website/landing/components/Showcase/Showcase.tsx

- Fix showcase preview size on smaller bps.
- Fix semantics.
1. Step A
2. Step B
3. Step C
-  [x] Ready to be merged

fix: landing - showcase preview size on smaller bps

---

website/landing/website.config.json

Fixing missing links and issues after proofreading

fix: content fixes on the landing page and in the docs

---

sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/presets/Sandpack.stories.tsx
sandpack-react/src/presets/Sandpack.tsx

external resources don't work on Sandpack component
external resources do work on Sandpack component

fix: external resources support

---

website/landing/components/common/Clipboard.tsx
website/landing/components/common/Resources.tsx
website/landing/styles/globalStyles.ts

- Removes scrollbar settings;
- Updates relative font sizes on smaller breakpoints;

fix: landing - global styles

---

website/landing/website.config.json

fix: leverege -> leverage

---

website/landing/components/Hero/HeroDesktop/HeroDesktop.tsx
website/landing/components/Hero/HeroMobile.tsx
website/landing/components/Intro/Sections/Custom.tsx
website/landing/components/Intro/Sections/Editor.tsx
website/landing/components/Intro/Sections/Layout.tsx
website/landing/components/Intro/Sections/Theme.tsx
website/landing/components/common/SandpackPreview.tsx
website/landing/website.config.json

Copy tweaks on the landing page based on Matan's feedback.

docs: copy tweaks

---

website/theme/components/footer/index.js

fix logo src

---

website/docs/docs/getting-started/custom-content.md

Small typo.
Documentation typo
- [X ] Documentation
- [X ] Ready to be merged

docs: small typo in custom-content.md

---

website/docs/docs/getting-started/custom-content.md

Documentation typo fix
Update `precious` -> `previous`
"N/A"

Update custom-content.md `precious` -> `previous`

---

website/docs/docs/getting-started/custom-ui.md

Documentation update
The import `codesandboxDarkTheme` is undefined.
This  PR updates `codesandboxDarkTheme` into `sandpackDark`

docs: update `codesandboxDarkTheme`

---

sandpack-react/src/components/CodeEditor/CodeEditor.stories.tsx
sandpack-react/src/components/CodeEditor/index.tsx
sandpack-react/src/components/CodeViewer/index.tsx
sandpack-react/src/components/FileTabs/FileTabs.stories.tsx
sandpack-react/src/components/FileTabs/index.tsx
sandpack-react/src/styles/index.css
website/landing/styles/globalStyles.ts

Removes the custom style for scrollbars and relies on the system configuration to whether shows the scrollbar or not.

fix(scrollbar): remove hijack custom style

---

LICENSE
package.json
sandpack-client/package.json
sandpack-react/package.json

Update the license from `GPLv3` to `Apache-2.0`.

chore: update LICENSE

---

sandpack-react/src/components/Preview/index.tsx
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/hooks/useLoadingOverlayState.ts
sandpack-react/src/presets/Playground.stories.tsx
sandpack-react/src/presets/Sandpack.stories.tsx

Init-mode (user-visible): it resets the bundler state when the client has been unregistered, which gives the loading component start a new loading flow from scratch

fix(init-mode): reset bundler state on unmount

---

website/docs/docs/community.md
website/docs/docs/faq.md
website/docs/docs/guides.md

The goal of the PR is to make our roadmap transparent, add a contribution guide, and more details of our open source approach for Sandpack.

feat(docs): community page

---

website/docs/docs/faq.md

Add some more clarification on server-side applications, what can be done and what's not.

fix(docs): add more clarification on server-side apps

---

sandpack-react/src/components/CodeEditor/CodeEditor.stories.tsx
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/presets/Playground.stories.tsx
sandpack-react/src/presets/Sandpack.tsx
sandpack-react/src/templates/angular.ts
sandpack-react/src/templates/index.tsx
sandpack-react/src/templates/react-typescript.ts
sandpack-react/src/templates/react.ts
sandpack-react/src/templates/svelte.ts
sandpack-react/src/templates/vanilla-typescript.ts
sandpack-react/src/templates/vanilla.ts
sandpack-react/src/templates/vue.ts
sandpack-react/src/templates/vue3.ts
sandpack-react/src/types.ts
sandpack-react/src/utils/sandpackUtils.ts

https://user-images.githubusercontent.com/4838076/152805376-bd38d31b-0a37-425b-a71f-b5ad85fd958c.mov

feat(type safe): custom setup

---

sandpack-react/src/components/index.ts

Component `FileExplorer` becomes exported.
`FileExplorer` is not usable, unlike, for example `FileTabs`.
`FileExplorer` would be exported and usable.
1. Start Storybook with `yarn storybook` and visit the `FileExplorer` stories: the component works as expected.
3. Build with `yarn build`

Export FileExplorer

---

.codesandbox/tasks.json

Update tasks.json for codesandbox

chore: update tasks.json [skip ci]

---

website/landing/next-env.d.ts
website/landing/package.json
yarn.lock

This will make the landing page work with our inspector.

chore: updates Next.js to 12.1.0

---

.github/workflows/csb-projects.yml

ci: CodeSandbox Projects support

---

sandpack-react/.storybook/preview.js
sandpack-react/src/Playground.stories.tsx

docs: storybook

---

sandpack-react/src/components/CodeEditor/CodeMirror.stories.tsx
website/docs/docs/guides/guides-overview.md
website/docs/docs/guides/integrate-monaco-editor.md

chores: typos

---

sandpack-react/src/types.ts

Fix: https://github.com/codesandbox/sandpack/issues/434

fix(custom-setup): add dev-dependencies

---

website/docs/docs/advanced-usage/components.md

docs(codeeditor): get codemirror instance

---

sandpack-client/.bundler

fix(client): update bundler version

---

sandpack-react/src/templates/index.tsx
sandpack-react/src/types.ts

fix(solid template): deprecate beta version

---

.gitignore
plugins/docusaurus/src/theme/CodeBlock/index.jsx
sandpack-react/src/components/CodeEditor/useSyntaxHighlight.ts
sandpack-react/src/components/CodeEditor/utils.ts
themes/README.md
themes/src/aquaBlue.ts
themes/src/githubLight.ts
themes/src/nightOwl.ts
website/docs/docs/getting-started/custom-content.md
website/docs/docs/getting-started/custom-ui.md
website/docs/docs/getting-started/ssr.md
website/docs/docs/getting-started/themes.md
website/docs/docusaurus.config.js
website/docs/package.json
website/docs/src/CustomSandpack.tsx
website/docs/src/scss/_code.scss
website/docs/src/scss/_menu.scss
yarn.lock

docs(themes): add examples and instructions

---

sandpack-react/src/contexts/sandpackContenxt.test.tsx
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/types.ts
sandpack-react/src/utils/sandpackUtils.test.ts
sandpack-react/src/utils/sandpackUtils.ts
website/docs/docs/advanced-usage/hooks.md

```js
// fix multiple updates in a row
sandpack.updateFile("/src/index.js", "fooo");
sandpack.updateFile("/src/styles.css", "bazzz");
// add support to multiple update in a single time
sandpack.updateFile({
"/src/index.js": "foo",
"/src/styles.css": { code: "bazz", readOnly: true },
});
```

fix(updatefile): support multiple files 

---

sandpack-react/src/contexts/sandpackContext.test.tsx
sandpack-react/src/contexts/sandpackContext.tsx

fix(updatefile): update all clients

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx

fix(inline-error): check if error message has a valid value

---

.github/workflows/release.yml
website/docs/src/NestedSandpack.tsx

chore(ci): remove major release script [skip ci]

---

README.md
sandpack-themes/README.md

chore(readme): update links [skip ci]

---

.github/workflows/checks.yml
sandpack-react/src/components/CodeEditor/CodeEditor.stories.tsx
sandpack-react/src/components/CodeEditor/CodeMirror.tsx
sandpack-react/src/components/CodeEditor/eslint.ts
sandpack-react/src/utils/array.test.ts
sandpack-react/src/utils/array.ts

fix(codemirror): remove inline props

---

.github/workflows/release-canary.yml
.github/workflows/release.yml
sandpack-client/.bundler
sandpack-react/src/index.ts

fix(release-script): trigger release

---

sandpack-react/src/types.ts

docs: turn some types public available [skip ci]

---

sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/types.ts

chore(context): remove renderHiddenIframe 

---

sandpack-react/src/contexts/sandpackContext.test.tsx
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/types.ts

feat(sandpack-context): add file method

---

website/docs/docs/getting-started/ssr.md

change docs to reflect new next ssr format

docs(ssr): update nextjs template

---

.github/workflows/csb.yml

_This pull request was created automatically by CodeSandbox._
Integrates the [Open in CodeSandbox](https://github.com/codesandbox/open-in-codesandbox) workflow. After merging this change, new pull requests will have helpful links appended to their description.

chore: add "Open in CodeSandbox" Links to PRs

---

.github/ISSUE_TEMPLATE/config.yml
.github/workflows/csb.yml

chore: redefine template issues

---

website/docs/docs/guides/guides-overview.md

docs: add guide for real time collab using firepad

---

sandpack-react/src/Playground.stories.tsx
sandpack-react/src/components/CodeEditor/__snapshots__/useSyntaxHighlight.test.tsx.snap

chore: playground

---

.codesandbox/tasks.json
website/docs/docs/guides/integrate-monaco-editor.md
website/docs/src/examples/Decorators.js

chore(docs): remove css link

---

website/docs/vercel.json

fix(docs): redirect double dash url

---

website/landing/components/Features/icons.tsx

Fix https://github.com/codesandbox/sandpack/issues/568

fix: website csb logo

---

sandpack-react/src/components/CodeEditor/useGeneratedId.ts

Closes https://github.com/codesandbox/sandpack/issues/575

fix(useGenerateId): improve useId conditional

---

sandpack-react/src/common/OpenInCodeSandboxButton/UnstyledOpenInCodeSandboxButton.tsx

Closes https://github.com/codesandbox/sandpack/issues/567

fix(track fork): standardized UTM parameter

---

sandpack-themes/src/cyberpunk.ts
sandpack-themes/src/index.ts

- adds new theme - cyberpunk
related to #596

feat(theme): add cyberpunk theme

---

sandpack-themes/src/index.ts
sandpack-themes/src/oceanBlue.ts

added new sandbox theme
https://github.com/codesandbox/sandpack/issues/596

feat: added oceanBlue theme

---

website/docs/docs/guides/integrate-monaco-editor.md

Trivial typo in the link to Advanced Usage
documentation
Existing
Existing
No steps. Documentation change

docs: Trivial spelling fix

---

sandpack-react/src/types.ts

```diff
/**
* @category Setup
*/
export type SandpackPredefinedTemplate =
| "angular"
| "react"
| "react-ts"
| "test-ts"
| "vanilla"
| "vanilla-ts"
| "vue"
| "vue3"
+  | "vue3-ts"
| "svelte"
| "solid";
```

fix: add predefined template

---

sandpack-react/src/Playground.stories.tsx
sandpack-react/src/presets/Sandpack.tsx

fix(sandpack preset): don't pass invalid props to React.Fragment 

---

sandpack-client/.bundler
sandpack-client/gulpfile.js

This removes some quite heavy but unused files from bundler, which is going to work alongside https://github.com/codesandbox/codesandbox-client/pull/7370

fix(bundler): ignore unused files

---

website/docs/src/NestedSandpack.tsx

https://sandpack.codesandbox.io/docs/getting-started/install
`website/docs/src/NestedSandpack.tsx`
line 48
```diff
customSetup={{
dependencies: {
-    "@codesandbox/sandpack-react": "1.0.0",
+    "@codesandbox/sandpack-react": "latest",
-    "@codesandbox/sandpack-themes": "1.0.0",
+    "@codesandbox/sandpack-themes": "latest",
},
}}
```
@danilowoz

feat: update docs sandpack deps

---

website/docs/src/pages/resources/faq.mdx

This PR adds a line about using Sandpack 2.0 for commercial purposes.

docs(License): add section about commercial usage

---

website/landing/website.config.json

docs: nodebox link

---

website/docs/src/pages/getting-started/layout.mdx

docs: fix link

---

sandpack-client/package.json

fix(sandpack-client): fixing package exports

---

package.json
sandpack-client/build.js
yarn.lock

fix(client): enable code-splitting and dynamic imports in esbuild

---

website/docs/src/pages/advanced-usage/client.mdx
website/docs/src/pages/advanced-usage/nodebox.mdx
website/docs/src/pages/getting-started/index.mdx
website/docs/src/pages/quickstart.mdx

Closes https://github.com/codesandbox/sandpack/pull/749

docs: correct yarn command

---

sandpack-client/src/clients/node/inject-scripts/consoleHook.ts
sandpack-react/src/components/Console/useSandpackConsole.ts

Resolves an issue where we're trying to send raw functions and data types through a message channel. I think we messed up encode vs decode? couldn't verify as the storybook seems broken
Closes https://github.com/codesandbox/nodebox-runtime/issues/8

fix: Send serialized console output to parent

---

website/docs/src/pages/advanced-usage/components.mdx

Documentation update
The word "dependencie" is used
The word "dependency" is used instead

fix "dependencie" typo

---

sandpack-react/package.json
sandpack-react/src/contexts/utils/useFiles.ts
yarn.lock

Closes https://github.com/codesandbox/sandpack/issues/772

fix(use-files): watch prop keys changes

---

sandpack-react/src/Playground.stories.tsx
sandpack-react/src/components/common/Loading.tsx

fix: open icon style with loading status

---

.codesandbox/ci.json
package.json
sandpack-client/package.json
sandpack-client/src/clients/node/index.ts
sandpack-react/src/Playground.stories.tsx
yarn.lock

Fix https://github.com/codesandbox/sandpack/issues/779

fix(nodebox): writeFile recursively 

---

sandpack-react/src/templates/index.tsx
sandpack-react/src/templates/node/vite-react-ts.ts
sandpack-react/src/templates/node/vite-svelte-ts.ts
sandpack-react/src/templates/node/vite-vue-ts.ts

Fixes #744
added ```vite-react-ts vite-svelte-ts vite-vue-ts```

fix: add vite-react-ts template

---

examples/gatsby/package.json

Closes https://github.com/codesandbox/sandpack/issues/759

docs(example): upgrade gatsby to 5

---

website/docs/src/pages/advanced-usage/nodebox.mdx

Updates example code for Nodebox and also adds link to the template 
1. Step A
2. Step B
3. Step C
- [ x] Documentation;

docs: Update example code for Nodebox and add link to starter

---

sandpack-react/package.json
sandpack-react/rollup.config.js
sandpack-react/scripts/rollup-generate-unstyled-types.js

fix: reference error with sandpack-react/unstyled in typescript

---

sandpack-react/src/templates/node/vite-react-ts.ts
sandpack-react/src/templates/node/vite-react.ts
sandpack-react/src/templates/node/vite-svelte-ts.ts
sandpack-react/src/templates/node/vite-svelte.ts
sandpack-react/src/templates/node/vite-vue-ts.ts
sandpack-react/src/templates/node/vite-vue.ts
sandpack-react/src/templates/node/vite.ts

Fixes https://github.com/codesandbox/nodebox-runtime/issues/32

chore: Update vite templates to use latest esbuild

---

sandpack-react/src/components/common/ErrorOverlay.tsx

Fix incorrect typings for ErrorOverlay
Closes #854

fix(types): incorrect typings for ErrorOverlay

---

sandpack-client/src/clients/runtime/index.ts
sandpack-client/src/clients/static/index.ts

Closes https://github.com/codesandbox/sandpack/issues/840

fix(clients): allow clipboard write

---

sandpack-react/src/components/Console/useSandpackConsole.ts

…ist in useSandpackConsole (#860)
Closes https://github.com/codesandbox/sandpack/issues/860

fix(console): add resetOnPreviewRestart to main useEffect hook

---

sandpack-client/src/clients/runtime/index.ts
sandpack-react/src/components/Console/Console.stories.tsx
sandpack-react/src/components/Console/SandpackConsole.tsx

Close https://github.com/codesandbox/sandpack/issues/859

fix(SandpackConsole): make showHeader flag works

---

sandpack-client/src/clients/static/index.ts
sandpack-client/src/clients/static/utils.ts

fix(static): Don't crash at inserting runtime

---

website/docs/src/pages/404.tsx
website/docs/src/pages/guides/_meta.json
website/docs/src/pages/guides/local-dependencies.mdx

Closes https://github.com/codesandbox/sandpack/issues/793

docs: how to load local dependencies

---

sandpack-react/package.json
sandpack-react/rollup.config.js
sandpack-react/src/components/Console/StdoutList.tsx
sandpack-react/src/contexts/utils/useClient.ts
sandpack-react/src/hooks/useSandpackClient.ts
sandpack-react/src/types.ts
sandpack-react/src/utils/ansi-to-react.ts
yarn.lock

Closes https://github.com/codesandbox/sandpack/issues/862

fix(react build): rename esm modules

---

sandpack-react/src/components/CodeViewer/index.tsx

Closes https://github.com/codesandbox/sandpack/issues/708

fix(code-viewer): support additionalLanguages 

---

sandpack-react/src/templates/runtime/react.ts

Fixes https://github.com/facebook/react/issues/26429#issuecomment-1476504730.

fix(react-template): update react-scripts to ^5.0.0

---

sandpack-react/src/components/Tests/Describes.tsx
sandpack-react/src/components/Tests/utils.ts

fix: verbose mode runtime error

---

sandpack-react/src/types.ts

Bugfix
Closes https://github.com/codesandbox/sandpack/issues/931
Compliant types as specified in docs.
1. Change locally in installed package
2. Use in project, where it was problematic

fix(types): deduplicate files type

---

sandpack-client/package.json
yarn.lock

Close https://github.com/codesandbox/sandpack/issues/930

fix(package.json): update @codesandbox/nodebox and outvariant versions

---

website/docs/src/pages/getting-started/usage.mdx

documentation update
SyntaxError

docs: fix SyntaxError

---

website/docs/src/pages/advanced-usage/components.mdx

documentation
The test file is not hidden in the "Hiding Tests" example
The test file is hidden in the "Hiding Tests" example

docs: fix for hiding test file

---

website/docs/src/pages/getting-started/index.mdx

Update Sandpack installation instructions to include both NPM and CDN usage.
1. Step A
2. Step B
3. Step C

docs: Update Sandpack installation instructions

---

.github/workflows/release.yml

fix: GitHub Publish script

---

website/theme/pages/index.js

Fix the broken link at https://sandpack.codesandbox.io/theme
Link direct to https://sandpack.codesandbox.io/docs/resources/community#contribution-guide

fix: update the broken link

---

.github/workflows/release.yml
sandpack-client/src/clients/node/inject-scripts/index.ts
sandpack-client/src/clients/node/inject-scripts/resize.ts
sandpack-react/src/Playground.stories.tsx

Hey, @davidmccabe. Here's the resize event implementation. 
Closes https://github.com/Sandpack/nodebox-runtime/issues/54

feat(node): Added resize event

---

website/docs/src/pages/getting-started/_meta.json
website/docs/src/pages/getting-started/private-packages.mdx

Adding clarification about updated private NPM plan availability to Sandpack docs

feat: Private NPM guidance update

---

sandpack-client/src/clients/runtime/index.ts
sandpack-react/src/Playground.stories.tsx

Close https://github.com/codesandbox/sandpack/issues/1088

fix(compile opts): don't overwrite default properties

---

sandpack-react/src/Playground.stories.tsx
sandpack-react/src/contexts/utils/useClient.ts

Close https://github.com/codesandbox/sandpack/issues/1058#event-11925657994

fix: investigating scroll issue

---

website/docs/src/pages/advanced-usage/components.mdx

fix(docs): update file explorer props table

---

sandpack-client/src/index.ts

Force new release using the new bundler that contains some module fixes

fix: force new release

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx

Fix regression introduce in https://github.com/codesandbox/sandpack/pull/1125

fix(codemirror): make sure extensions & theme is applied when init

---

examples/nextjs-app-dir/components/sandpack-examples.tsx
sandpack-react/package.json
sandpack-react/rollup.config.js
yarn.lock

Close https://github.com/codesandbox/sandpack/issues/1152

feat(react): enable use client directive

---

.github/workflows/release.yml
CHANGELOG.md
examples/nextjs-app-dir/components/sandpack-examples.tsx
lerna.json
sandpack-client/.bundler
sandpack-client/CHANGELOG.md
sandpack-client/package.json
sandpack-client/src/clients/node/client.utils.ts
sandpack-client/src/clients/runtime/index.ts
sandpack-react/CHANGELOG.md
sandpack-react/package.json
sandpack-react/rollup.config.js
sandpack-react/src/PrivatePackage.stories.tsx
sandpack-react/src/components/common/OpenInCodeSandboxButton/UnstyledOpenInCodeSandboxButton.tsx
sandpack-react/src/presets/CustomSandpack.stories.tsx
sandpack-react/src/types.ts
website/docs/src/pages/advanced-usage/serving-static-files.mdx
yarn.lock

feat: Add support for enabling service worker feature

---

.github/PULL_REQUEST_TEMPLATE.md
website/docs/package.json
website/docs/src/components/CodeBlock.tsx

fix(docs): update sandpack version

---

website/docs/src/pages/advanced-usage/hooks.mdx

Closes https://github.com/codesandbox/sandpack/issues/1176

docs: add example for useSandpackClient

---

sandpack-react/src/components/CodeEditor/CodeMirror.stories.tsx
sandpack-react/src/components/CodeEditor/CodeMirror.tsx

Closes https://github.com/codesandbox/sandpack/issues/1178
@danieldelcore, thank you for reporting this issue.

fix(code editor): remount when readOnly change

---

sandpack-client/src/clients/runtime/index.ts
sandpack-client/src/clients/static/index.ts

Closes https://github.com/codesandbox/sandpack/issues/1182

feat(iframe allow): introduce xr-spatial-tracking

---

sandpack-react/src/Playground.stories.tsx
sandpack-react/src/components/FileTabs/index.tsx

fix(file-tab): close button
