codesandbox/sandpack

sandpack-client/package.json
sandpack-client/src/client.ts
sandpack-client/src/file-resolver-protocol.ts
sandpack-client/src/iframe-protocol.ts
sandpack-client/yarn.lock
sandpack-react/package.json
sandpack-react/src/contexts/sandpack-context.tsx
sandpack-react/yarn.lock

Simplifies the listen/dispatch flows:
- no need to wait for iframe handshake, global listener can wait for the initialized message
- the dispatch does not trigger the listeners from the sandpack-client (eg: compile)
- added some cleanup code so no listeners are left as components are mounted/unmounted
- class implementation ensures no code is executed before it is needed (eg: before sandpack is running)
closes #12

drop codesandbox-api in favor of a custom solution

---

sandpack-client/src/client.ts
sandpack-client/src/file-resolver-protocol.ts
sandpack-client/src/types.ts
sandpack-client/src/utils.ts
sandpack-react/src/common/LoadingOverlay.tsx
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/hooks/useErrorMessage.ts
sandpack-react/src/hooks/useLoadingOverlayState.ts
sandpack-react/src/types.ts

closes #32 - head tag replacing the original html head in the bundler on the first load
closes #14 - more information shown on runtime errors
closes #15 - option set to false in sandpack-client, can later be overwritten
closes #16 - inside the bundler

error screen details and small fixes

---

sandpack-playground/src/App.tsx
sandpack-playground/src/index.html

Made a quick example of how to update the style from the sandpack components. removed the border around the layout so 100vh on the editor is 100vh for the entire component

fix: style customization for playground component

---

sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/hooks/useLoadingOverlayState.ts
sandpack-react/src/types.ts

Had to lift the timeout calculation to the sandpack context because the hook can be mounted before the client is instantiated (eg: when not using the autorun option)

fix: loading timeout only counted after the client is instantiated

---

sandpack-client/gulpfile.js
sandpack-client/package.json
sandpack-react/package.json
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/presets/CustomSandpack.stories.tsx

Basically, the main problem with not registering the listener was because the client was created after the listening has been added. So, I created a new object in the `queuedListeners` called `global`, to take care of all the events that must be added to clients, regardless of when. So I guess we cover the following cases:
- Set a listener, but the client hasn't been created yet;
- Set a listener, but the client has already been created;
- A client already exists, set a new listener and then one more client has been created;
Closes #71

Listener is missing to register emit

---

sandpack-react/README.md
sandpack-react/src/components/CodeEditor/CodeEditor.stories.tsx
sandpack-react/src/components/CodeEditor/CodeMirror.tsx
sandpack-react/src/components/CodeEditor/highlightInlineError.ts
sandpack-react/src/components/CodeEditor/index.tsx
sandpack-react/src/components/CodeEditor/utils.ts
sandpack-react/src/presets/Sandpack.stories.tsx
sandpack-react/src/presets/Sandpack.tsx

https://user-images.githubusercontent.com/4838076/125803444-744736d3-7f94-4c8a-b164-c6aed1f108ae.mov
It introduces a new prop `showInlineErrors` which basically consumes the error logs from the bundler and highlights it in the Codemirror using the class name`cm-errorLine`, which will allow customization on top of this feature.
How it works:
- Basically, a new plugin was created to handle the decoration in the editor, and this plugin listen to changes from the editor;
- Then, a new sandpack listener was introduced to listen to the bundler error and pass these messages to the editor through `annotations` changes;
- Once all errors are solved, the listener triggers a new code change (with the same input and same selection values), just to clean up the decoration - kind of a hack, but it …

feat(react): syntax inline error - CSB-735

---

sandpack-react/README.md
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/presets/Sandpack.stories.tsx
sandpack-react/src/types.ts

It implements the ability to reset the files for the original values from `props`. The following methods were added to the context:
| Method | Description |
| - | - |
| `resetAllFiles` | Reset all files for all paths               |
| `resetFile`     | Reset the code for a given path             |
CSB-829

feat(usesandpack): reset-file and reset-all-files CSB-829

---

package.json
sandpack-react/src/common/ErrorOverlay.tsx
sandpack-react/src/components/CodeEditor/CodeMirror.tsx
sandpack-react/src/components/FileTabs/index.tsx

This avoids Google Translate translating the code editor and the error messages, but the UI components still going to be translated, like the "Run sandbox" button and "Open on CodeSandbox". 
---
CSB-1593 - Related to https://github.com/reactjs/reactjs.org/issues/3977

fix(react): do not translate code blocks and error messages

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx

The instructions elements ids in each code block must be unique, otherwise you will get the following HTML errors if you use more than one code block on web page: 
> Duplicate ID “enter-instructions”.
> The id attribute is used to identify a single element within a document, and is required to be unique. Check the document for repeated IDs.
When I try to check the site with the W3C Validator, I get the "Duplicate ID" errors (see https://validator.w3.org/nu/?doc=https%3A%2F%2Fbeta.reactjs.org%2Flearn for example).
No any "Duplicate ID" errors when validator checks web page that contains multiple code blocks.
1. Include two code blocks on same web page
2. Try to validate final HTML markup on https://validator.w3.org/
3. Make sure that no "Duplicate ID" errors such have been detected

fix(react): make instructions elements ids unique

---

.gitignore
sandpack-client/src/client.ts
sandpack-client/src/utils.ts
sandpack-react/src/presets/Sandpack.stories.tsx
sandpack-react/src/templates/index.tsx
sandpack-react/src/templates/react-typescript.ts
sandpack-react/src/types.ts
sandpack-react/src/utils/sandpackUtils.ts

Resolves #108 
Provide a predefined template for react with out-of-the-box support for typescript
Extended Storybook
The public API of 'sandpack-client' has changed (added new param for 'devDependencies'). Not sure how the release process works but the `ts-ignore` from `sandpackUtils.ts` has to go.
Also prettier added some formatting but I can only assume the previous code was incorrectly formatted.

feat(template): add react typescript

---

sandpack-react/src/presets/Sandpack.stories.tsx
sandpack-react/src/templates/index.tsx
sandpack-react/src/templates/vanilla-typescript.ts
sandpack-react/src/types.ts

Resolves #127 
Provides a sandpack template with out-of-the-box support for typescript.
Technically it is similar with the existing "vanilla" sandpack template, but with `.ts` files instead of `.js`.
The resulted sandbox follows the "Vanilla Typescript" codesandbox template.
Extended Storybook

feat(template): add vanilla typescript

---

sandpack-client/src/client.ts
sandpack-react/src/contexts/sandpackContext.tsx
website/docs/docs/advanced-usage/client.md
website/docs/docs/getting-started/custom-content.md

Here is the implementation of the feature request [119](https://github.com/codesandbox/sandpack/issues/119): 
> Expose the externalResources in sandpack-client and sandpack-react.
There is not possible to specify the external resources such as CSS files or images existing somewhere in the web.
It would be possible to include the links to external resources via options in sandpack-client or sandpack-react:
```jsx
<Sandpack 
template="react"
files={{
"/App.js": reactButtonCode,
"/button.js": buttonCode,
}}
options={{
openPaths: ["/App.js", "/button.js", "/index.js"],
activePath: "/index.js",  
externalResources: [
"https://unpkg.com/@tailwindcss/ui/dist/tailwind-ui.min.css"
]
}} />
```
1. Create React project
2. Install Sandpack via `yarn add @codesandbox/sandpack-react`
3. Add the …

feat(client): expose of the externalResources

---

website/landing/components/common/Clipboard.tsx
website/landing/website.config.json

- Improves clipboard copy feedback (toast);
- Fixes dimensions of CodeHike's logo;

feat(landing): misc tweaks

---

website/landing/components/Hero/Hero.tsx
website/landing/components/Hero/HeroDesktop.tsx
website/landing/components/Hero/HeroMobile.tsx
website/landing/components/Hero/heroSandpackFiles.ts

Re-creates hero within Sandpack for large screens. This is the final state of the hero animation, the pieces will be put together in a following PR.
https://user-images.githubusercontent.com/24959348/143180664-771e09a5-1bee-4874-959a-225c2369f69a.mov
- Manual verification on viewports above 1440px;

feat: landing - hero desktop using sandpack

---

website/docs/src/NestedSandpack.tsx
website/docs/src/scss/_code.scss

@sannek here is the vertical component. I would like to customize more the second preview but that will require not used the Sandpack component and loose all the default styles. Maybe in a next iteration?

Vertical component for nested sandpack on the documentation

---

sandpack-react/src/components/CodeEditor/utils.ts
sandpack-react/src/presets/Sandpack.stories.tsx
sandpack-react/src/templates/index.tsx
sandpack-react/src/templates/svelte.ts
sandpack-react/src/types.ts

It provides better syntax highlighting for `.svelte` files
Currently, `.svelte` files are being associated as javascript files.
Instead of javascript, `.svelte` files will be associated with html files since they are more similar.
1. Added a case for svelte in the extensions switch case.
Loving the project!! <3

feat(template): svelte 

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx
website/landing/package.json

When `initMode` is on `user-visible` or `lazy` mode, there is no placeholder rendered in place of the Codemirror editor. So this PR ensures that there is always a kind of component with the `code` being rendered regardless the of the editor status.

fix(init-mode): render placeholder

---

website/docs/docs/getting-started/custom-ui.md
website/docs/src/NestedSandpack.tsx

The banner to the Sandpack Theme Builder is the only major change in this PR:

docs: add theme builder

---

website/landing/components/Hero/HeroDesktop/HeroDesktop.tsx

Fixes cropped tab on the hero's editor.
[x] Chrome
[x] Safari
[x] FF

fix: landing - cropped editor tabs on hero editor

---

website/docs/docs/intro.md

Small content fix  Updated the Arrows on the documentation Page
**Old Arrows**
FileExplorer is not usable, unlike, for example FileTabs.
**New Arrows**
Checked diffrent browsers 
###Documentation N/A
Ready to be merged

docs: changed the arrows

---

sandpack-react/src/components/CodeEditor/CodeEditor.stories.tsx
sandpack-react/src/components/CodeEditor/CodeMirror.stories.tsx
sandpack-react/src/components/CodeEditor/utils.ts
sandpack-react/src/components/CodeViewer/CodeViewer.stories.tsx
sandpack-react/src/components/CodeViewer/index.tsx
sandpack-react/src/components/FileExplorer/FileExplorer.stories.tsx
sandpack-react/src/components/FileExplorer/index.tsx
sandpack-react/src/components/FileTabs/FileTabs.stories.tsx
sandpack-react/src/components/FileTabs/index.tsx
sandpack-react/src/components/Navigator/Navigator.stories.tsx
sandpack-react/src/components/Navigator/index.tsx
sandpack-react/src/components/Preview/Preview.stories.tsx
sandpack-react/src/components/Preview/RefreshButton.tsx
sandpack-react/src/components/Preview/index.tsx
sandpack-react/src/components/TranspiledCode/TranspiledCodeView.stories.tsx
sandpack-react/src/components/TranspiledCode/index.tsx

TS types fix
Most of the react components implemented the React.FC type, implying they accept `children` while they actually don't.
React.FC in still supported by react for backwards compatibility, but has been recognised officially as an anti-pattern for a while.
Here are some readings about this:
- https://github.com/typescript-cheatsheets/react#function-components (section "Why is `React.FC` discouraged?")
- https://kentcdodds.com/blog/how-to-write-a-react-component-in-typescript
- https://dev.to/wojciechmatuszewski/top-three-react-typescript-pitfalls-50l8
- https://fettblog.eu/typescript-react-why-i-dont-use-react-fc/
Components are not falsely types as supporting children.
Additionally, react imports have been unified to the `import * from React` pattern that seem to be used in the …

fix(types): react components not actually accepting children

---

website/landing/components/Intro/Sections/Custom.tsx
website/landing/components/Intro/Sections/Editor.tsx
website/landing/components/Intro/Sections/common.tsx

1. Fix a bug blocking interaction with editors due to invisible elements overlapping
2. Dim reset button when the editor contents are unchanged
1. 
https://user-images.githubusercontent.com/4658208/145232138-43761d11-8c49-4088-9f7b-6d36dd582a5e.mp4
2. Reset button gives the impression that the reset button will do _something_ while it's visible.
1. Invisible elements are given `pointerEvents: "none"`.
2. Reset button is dimmed if editor contents are unchanged.
Locally tested both interactions:
1. Reset button now works consistently.
2. Reset button is dimmed until changes are made in the editor.
https://user-images.githubusercontent.com/4658208/145233783-d87b7943-ff6f-452a-9906-43738de195fa.mp4

fix(landing): set pointerEvents to avoid reset button overlap

---

sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/presets/CustomSandpack.stories.tsx
sandpack-react/src/types.ts
website/docs/docs/advanced-usage/provider.md

It exposes the `clients` map under the same contexts, which gives the possibility to interact with all clients under the same provider. Providing access to the clients allows to communicate with the iframe elements and pass messages.
This is the safest way to interact with clients and their iframes, as Sandpack context ensures access to all Preview that has been rendered under the same provider.

fix(react-context): expose clients 

---

plugins/docusaurus/src/theme/CodeBlock/index.jsx
plugins/docusaurus/src/theme/CodeBlock/style.css
website/landing/components/common/Clipboard.tsx

Adds a copy button on CodeBlock:

docs(codeblock): add copy button

---

.codesandbox/project.json
sandpack-react/src/components/FileTabs/FileTabs.test.tsx
sandpack-react/src/components/FileTabs/index.tsx
sandpack-react/src/components/FileTabs/utils.tsx
sandpack-react/src/templates/Templates.stories.tsx
sandpack-react/src/templates/react-typescript.ts
sandpack-react/src/types.ts
sandpack-react/src/utils/stringUtils.test.ts
sandpack-react/src/utils/stringUtils.ts

- Unify `react-ts` and `react` template format, in order to avoid mistakes on the pathname;
- Introduce a function to avoid filename conflicts or having duplicates file name in the FileTabs;
- Improve documentation about entry point;
Closes #250

fix(entry/files): prevent mismatch with pathname 

---

sandpack-client/src/client.ts
sandpack-client/src/types.ts
sandpack-react/src/components/ReactDevTools/index.tsx
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/types.ts

This explicitly consumes the legacy version of `react-devtools-inline@4.40` implemented in the CodeSandbox bundler. We have been implementing the ability to consume versions of the React DevTools differently in order to have backward compatibility in the codesandbox.io and support the latest releases of React.

fix(react-devtools): legacy mode

---

website/docs/docs/guides.md

This introduces a new section in the documentation, which is related to guides, recipes, or examples. The idea is to introduce some basics (but very common) implementation, and later we can improve this content by turning them in tutorials.

docs(guides): add page

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx

Refactors to improve the condiction around when the editor should be mounted and unmounted. Previously, the Editor has been destroying every time it was out of the viewport (which was causing layout shift very often), plus this is an unnecessary step, because once the editor is mounted there is no advantage of destroying and mounting it again. 
Closes #293

fix(init-mode): avoid unnecessary unmonted state

---

sandpack-react/src/icons/Icons.stories.tsx
sandpack-react/src/icons/index.tsx
sandpack-react/src/index.ts

Exports all Sandpack icons to be used for third apps, this will provide a more consistent way to implement interfaces. 
Closes #287

feat(icons): export sandpack icons

---

sandpack-client/src/types.ts
sandpack-react/src/components/CodeEditor/CodeEditor.stories.tsx
sandpack-react/src/components/CodeEditor/CodeMirror.tsx
sandpack-react/src/components/CodeEditor/index.tsx
sandpack-react/src/components/CodeViewer/index.tsx
sandpack-react/src/components/FileTabs/FileTabs.stories.tsx
sandpack-react/src/components/FileTabs/index.tsx
sandpack-react/src/hooks/useActiveCode.ts
sandpack-react/src/presets/Playground.stories.tsx
sandpack-react/src/presets/Sandpack.tsx
sandpack-react/src/styles/index.css
sandpack-react/src/types.ts
website/docs/docs/getting-started/custom-content.md

This introduces a read-only mode by file or for the entire project. 
Closes #296
Closes #97

feat(files): read-only mode

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx

This shifts the approach used to replace the `placeholder` codebase to the CodeMirror editor. The previous implementation was using a React state which, for a moment, the editor didn't have any codebase at all. From now on, I brought back the previous implementation, which uses DOM API to remove the placeholder in the right moment of the CodeMirror is created, which is way faster than a React DOM flow.

fix(codemirror): shift approach to remove placeholder

---

.codesandbox/workspace.json
sandpack-react/package.json
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/types.ts

Shift the approach of how the `editorState` has been updated in the Sandpack context. From now on, it watches any changes on files and then sets if the current editor has any changes performed internally. 
Closes #332

fix(editorstate): watch changes on files instead of each method

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx
sandpack-react/src/components/CodeEditor/utils.ts

It adds the language extension as a class name in the editor component, which gives more possibilities for customizations.

fix(codemirror): adds language extension as classname

---

sandpack-client/src/iframe-protocol.ts

Fixes an issue with multiple sandboxes on the same page (or any other iframes)
iframe-protocol emits event from each iframe to each client (so 3 sandboxes results in 9 events... exponential growth)
Filters based on evt.source to ensure event is coming from the iframe the iframe-protocol is pointed at
1. Add a bunch of sandboxes on one page
2. Log incoming events
3. See that it no longer spams console with events :)

fix: Filter out events originating from different iframes

---

.codesandbox/tasks.json

Was doing some testing with the new tasks feature, so I figured I can also PR the config changes.
The new tasks.json was auto generated so it's a bit mixed up, but it keeps all previously configured tasks and previews and sets the storybook command to run on container start

chore: update csb config

---

sandpack-react/src/contexts/sandpackContext.tsx

This is a nested update. Nested updates are bad for performance. They're also always sync, which isn't good for hydration.
In this case the whole pattern is unfortunate. Instead of a nested update, this should use `getDerivedStateFromProps`. But for now, this is an OK workaround that should improve perf.

fix: don't make unnecessary sync updates

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx
sandpack-react/src/components/CodeViewer/CodeViewer.stories.tsx

Bug fix
Pass down decorators without sort by line will cause codemirror error.
https://github.com/codesandbox/sandpack/issues/383
decorators without sort will work fine
I did not find component unit tests, so I edit the storybook a little to reproduce this problem, and fix the code to make it work.
By the way, is there any plan to add unit tests? I can also do some help if needed.

fix: sort decorators before pass to codemirror

---

sandpack-react/src/common/ErrorOverlay.tsx
sandpack-react/src/common/Loading.tsx
sandpack-react/src/common/LoadingOverlay.tsx
sandpack-react/src/common/RunButton.tsx
sandpack-react/src/common/Stack.tsx
sandpack-react/src/components/CodeEditor/index.tsx
sandpack-react/src/components/CodeViewer/index.tsx
sandpack-react/src/components/FileExplorer/index.tsx
sandpack-react/src/components/FileTabs/index.tsx
sandpack-react/src/components/Navigator/index.tsx
sandpack-react/src/components/Preview/index.tsx
sandpack-react/src/components/ReactDevTools/index.tsx
sandpack-react/src/components/TranspiledCode/index.tsx
sandpack-react/src/presets/CustomSandpack.stories.tsx
sandpack-react/src/presets/Sandpack.tsx

- Accept className props;
- Rename `customStyle` to `style`;
- Add proper Typescript types based on HTML element;

fix: standardize components 

---

sandpack-react/package.json

- bug fix, the `@codesandbox/sandpack-react` package requires users to import the css file (`import "@codesandbox/sandpack-react/dist/index.css"`), which would be removed after tree shaking
-  style from css would be removed after tree shaking
-  style from css would not be removed after tree shaking
- would occur in any projects use `@codesandbox/sanpack-react` using tree shaking

fix: side effect should contain css

---

website/docs/docs/guides/_category_.json
website/docs/docs/guides/guides-overview.md
website/docs/docs/guides/integrate-monaco-editor.md

Introduces a guide to integrate Monaco editor in place of the CodeMirror #327 
Currently we only have one Guides page
This PR adds a section called Guides, where we can add more guides in the future
Let me know if you like this format or if you have any suggestions, thanks 👍.

docs: add monaco editor guide

---

sandpack-client/src/client.ts
sandpack-react/src/contexts/sandpackContext.tsx

**Problem:** 
The iframe assigns a new URL in a manner that adds a new entry to the browser's list of visited URLs, on Firefox. 
**Solution:** 
So, instead of manipulating the iframe dom and adding/removing the `src` attribute, it manipulates the iframe browser history.
Fixes https://github.com/codesandbox/sandpack/issues/398
Useful links:
- https://github.com/aFarkas/lazysizes/commit/512800de6ebddf6a5000624b67f86c4f0d77d8c6
- [stackoverflow.com/questions/2245883/browser-back-acts-on-nested-iframe-before-the-page-itself-is-there-a-way-to-av](https://stackoverflow.com/questions/2245883/browser-back-acts-on-nested-iframe-before-the-page-itself-is-there-a-way-to-av)

fix(client): prevent add route into the main page browser history

---

sandpack-react/src/types.ts

Remove all values from environments type that **is not runtime**, meaning it needs a server to run (not supported by Sandpack).

fix(environment): remove sse envs

---

.github/PULL_REQUEST_TEMPLATE.md
sandpack-react/src/components/Preview/Preview.stories.tsx
sandpack-react/src/components/Preview/index.tsx
website/docs/docs/advanced-usage/components.md

This PR enables users to add more buttons to the preview area. They will be rendered right before buttons for "Refresh" and "Open in CodeSandbox".
Users can't add custom buttons to preview.
User can add a button in the following way:
```jsx
<SandpackPreview
additionalButtons={
<button
className="sp-button"
style={{ padding: 'var(--sp-space-1) var(--sp-space-3)' }}
onClick={() => window.alert('Bug reported!')}>
Report bug
</button>
}
/>
```
Manually tested in the documentation and in a personal project.

feat: Add slot for additional buttons

---

sandpack-client/src/client.ts

It provides a default value for the `logLevel` on sandpack-client. I see many unexpected logs coming from the bundler that we can't rid of. @DeMoorJasper if someone set `logLevel` to none, will they still receive these logs through iframe-protocol?

fix(loglevel): set default

---

LICENSE

Actually adds the company information to the license, as it's probably not really valid right now?

fix: Add year and company name to license

---

sandpack-react/src/components/Preview/Preview.stories.tsx
sandpack-react/src/components/Preview/index.tsx
website/docs/docs/advanced-usage/components.md

Imperatively retrieve the Sandpack client from a SandpackPreview:
```jsx
const SandpackClient: React.FC = () => {
const { sandpack } = useSandpack();
const previewRef = React.useRef<SandpackPreviewRef>();
React.useEffect(() => {
const client = previewRef.current?.getClient();
const clientId = previewRef.current?.clientId;
if (client && clientId) {
console.log(client);
console.log(sandpack.clients[clientId]);
}
}, [sandpack]);
return <SandpackPreview ref={previewRef} />;
};
```
I agree that currently there is no way to get the current client id and the client instance from a preview component, and it might be too restrictive for a few cases. Although we already have available the list of all clients, currently I can't see a way to link a client from the list to a component, so hope that …

feat(preview): consume client 

---

sandpack-client/src/file-resolver-protocol.ts

Errors result in messages not receiving a response
Errors are returned back to the bundler
Rebuild the protocol from the ground up, there's a few things that might cause issues.

feat: file-resolver protocol error handling

---

sandpack-client/package.json
sandpack-client/src/client.ts
sandpack-react/src/Playground.stories.tsx
sandpack-react/src/presets/Sandpack.tsx
sandpack-react/src/templates/index.tsx
sandpack-react/src/templates/solid.ts
sandpack-react/src/types.ts
yarn.lock

feat(template): add solidjs (beta)

---

cypress/integration/Issues.spec.js
sandpack-react/src/Issues.stories.tsx
sandpack-react/src/components/CodeEditor/CodeMirror.tsx

Closes https://github.com/codesandbox/sandpack/issues/454

fix(readonly): toggle remounting

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx
sandpack-react/src/components/CodeEditor/useGeneratedId.ts

Haven't actually tested but we need to do this. I see mismatches otherwise.
I tried to keep it backwards-compatible. If you drop 17 support then you can just useId.

fix(editor): prefer useId when available

---

sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/contexts/themeContext.tsx
sandpack-react/src/types.ts
website/docs/docs/releases/v1.md
website/landing/components/Hero/HeroDesktop/HeroDesktop.tsx
website/landing/components/Intro/Examples.tsx

fix(theme context component): extend props support

---

package.json
sandpack-react/src/components/CodeEditor/CodeEditor.stories.tsx
sandpack-react/src/components/CodeEditor/CodeMirror.tsx
sandpack-react/src/components/CodeEditor/eslint.ts
sandpack-react/src/contexts/sandpackContext.test.tsx
sandpack-react/src/utils/array.test.ts
sandpack-react/src/utils/array.ts
yarn.lock

Address https://github.com/reactjs/reactjs.org/issues/4686#issuecomment-1137402613
All `useEffect` which depends on inline default props (`extensions` and `extensionsKeymap`), were constantly being triggered unnecessarily due to these props always returning a new value every time that the parent rerender.  
@gaearon does it make sense? 
----
Note to me: apply these changes on `main` too.

fix(codemirror): remove inline props

---

sandpack-react/src/Playground.stories.tsx
sandpack-react/src/contexts/themeContext.tsx
sandpack-react/src/presets/Sandpack.test.tsx

It infers the main surface color from the theme and sets the properly `color-scheme: dark | light` in order to make sure the scrollbars have the suitable theme too. 
Closes #489

fix(theme): set color-scheme css property in theme context

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx
sandpack-react/src/components/CodeEditor/highlightInlineError.ts

It refactors the extension to show inline error on Codemirror and fixes a bug that dismisses tooltips.

fix(code-editor): improve showInlineError extension integration

---

sandpack-client/src/iframe-protocol.ts
sandpack-react/src/Playground.stories.tsx
sandpack-react/src/contexts/sandpackContext.test.tsx
sandpack-react/src/contexts/sandpackContext.tsx

Make sure that all listeners are not unexpectedly discarded when a listener is unsubscribed. 
Issue is described here: https://github.com/reactjs/reactjs.org/issues/4768
- From now on, `unregisterBundler` is responsible for removing all listeners for a given client;
- An unsubscribing action no longer remove all listeners from the queue;
Closes #513

fix(global-listeners): doesn't unsubscribe all listener unexpectedly 

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx
sandpack-react/src/components/CodeEditor/index.tsx

Hey @joshwcomeau, this PR addresses your bug report about the ability to override the `extensionsKeymap`. Turns out, it was a mistake on our side and we were literally inserting a `tab` instead of regularly indenting the line. So, this should fix your original problem and make the CodeEditor behavior more consistent.
Closes #522

fix(codemirror): use correct method to indent the code on tab key press

---

website/landing/components/Hero/HeroDesktop/HeroDesktop.tsx

Tiny CSS layout bug fix
On a larger monitor (3377 x 1304) the description overlaps the top links, making it impossible to interact with the links. This can be "resolved" by scrolling down the page, but they're not interactive on initial load.
Added a `z-index` CSS property to the parent container of the interactive content to ensure it's above the description and thus interactive.
1. Added the same CSS in the browser dev tools and was able to resolve the issue
2. Removed the CSS in the browser dev tools and was able to see the issue re-appear
- added `zIndex: 1` to the parent container of the header links to ensure they are interactive. This specifically targets larger screen sizes where the description overlaps the `Clipboard` and `Resources` content

Update HeroDesktop.tsx to fix link access

---

sandpack-client/.bundler
sandpack-react/src/presets/CustomSandpack.stories.tsx

fix(client): custom registry should include the credentials only for csb urls 

---

sandpack-react/src/components/FileExplorer/File.tsx
sandpack-react/src/components/FileExplorer/FileExplorer.stories.tsx
sandpack-react/src/presets/Sandpack.test.tsx
sandpack-react/src/styles/shared.ts

fix(file-explorer): trim and avoid shrinks the icon on long file names

---

.codesandbox/ci.json
sandpack-client/src/client.ts
sandpack-react/src/Issues.stories.tsx

Fixed https://github.com/codesandbox/sandpack/issues/561
Sandpack client intercepts the "refresh" dispatch in order to make sure that the iframe is still in the location it's supposed to be. External links inside the iframe will change the location and prevent the user from navigating back.

fix(client-navigation): make sure iframe is using the right location on refreshing 

---

sandpack-client/src/utils.test.ts
sandpack-client/src/utils.ts
sandpack-react/src/Issues.stories.tsx
sandpack-react/src/Playground.stories.tsx
sandpack-react/src/contexts/sandpackContext.test.tsx
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/utils/sandpackUtils.test.ts
sandpack-react/src/utils/sandpackUtils.ts

Closes #353
Normalizes leading slash on paths looks necessary to make the file tree state and the ability to overwrite template files more reliable. I've noted many cases where a mistyping might lead to the wrong sandbox configuration, especially when this file is a `package.json`. 
Features:
- Introduces `normalizePath` function to ensure leading slash on paths;
Fixes:
- Normalizes path on adding new files to the Sandpack context;
- Make sure custom entry overwrite `main` value on `package.json` file;
- Normalizes `activeFile` and `visibleFiles`: it used to return values that didn't match with the file tree;
- `activeFile` and `visibleFiles` have been ignored when the content was an empty string;

fix(files): normalize paths

---

sandpack-themes/src/atomDark.ts
sandpack-themes/src/index.ts

Publish a theme that inspired from [atom-dark-syntax](https://github.com/atom/atom-dark-syntax)
1. Tested build after adding `atomDark.ts` and modifying `sandpack-themes/src/index.ts`, working as expected.

feat(theme): atom dark ⚛

---

sandpack-react/src/presets/Sandpack.tsx

Bug fix
Currently getting this error when using Sandpack React:
```
Invalid prop `style` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.
```
I traced back the error back to this point in the code.
Don't apply the `style` prop to `React.Fragment`
It seemed fine in CodeSandbox projects, but I have done no more testing. Please check everything works!

fix: style prop no longer passed to React.Fragment

---

sandpack-themes/src/index.ts
sandpack-themes/src/levelUp.ts

I'm having a blast creating Sandpack themes using the theme builder! One of the two themes I've created for today adapts [the Level Up Tutorials VSCode theme](https://marketplace.visualstudio.com/items?itemName=leveluptutorials.theme-levelup) into Sandpack.
I ported the Level Up Theme using the Sandpack Theme Builder. Here's a screenshot of the theme in Storybook:
1. Verified the new theme via Storybook

feat(theme): Level Up Theme

---

package.json
yarn.lock

update package-build-stats to newer version for deleting node-sass package.
yarn install node-sass with long time.
shorten installation time
related to https://github.com/codesandbox/sandpack/issues/614

chore: update package-build-stats to 7.3.13

---

website/docs/docs/getting-started/ssr.md

Small bug fix
Gatsby complains with:
```shell
Warning: Each child in a list should have a unique "key" prop.
```
Adding a `key` to the style tags ensures that React has a non-null value for `key`.
Running a Gatsby site locally with that script

chore(docs): Add `key` to SSR snippets

---

sandpack-client/.bundler
sandpack-react/src/templates/Templates.stories.tsx
sandpack-react/src/templates/vue3.ts

Related https://github.com/codesandbox/codesandbox-client/issues/6762

fix(vue template): support script setup template

---

sandpack-react/src/contexts/sandpackContext.tsx

Bug fix
https://github.com/codesandbox/sandpack/issues/651
If "addFile" is called with a falsy 'code' value or not passed at all (since it is an optional prop), the file will not be created.
If 'code' prop is not passed at all, we no longer check that 'code' is truthy. This mean that the existing check:
```
code === this.state.files[pathOrFiles].code
```
would return true if 'code' argument was not passed at all, since undefined === undefined. We do not want this.
So we have introduced one extra check to ensure that we are comparing an existing file in the first place from 'this.state.files[pathOrFiles].code'.
```
if ( this.state.files[pathOrFiles]?.code && code === this.state.files[pathOrFiles].code )
```
This means that if a file doesn't exist already, we will never short circuit and …

fix(sandpack-context): addFile with no code argument

---

website/docs/docs/getting-started/custom-ui.md

I updated the link to the 'classer' repository on [this documentation page](https://sandpack.codesandbox.io/docs/getting-started/custom-ui) as it was previously bringing you to a 404 page.
The link currently brings you to a 404 page.
The link brings you to the GitHub repository for the classer package.
1. I visited the link to make sure it works.
- [NA] Documentation;
- [NA] Storybook (if applicable);
- [NA] Tests;

Update the link to the 'classer' repository

---

sandpack-react/src/Issues.stories.tsx
sandpack-react/src/utils/sandpackUtils.test.ts
sandpack-react/src/utils/sandpackUtils.ts

`activeFile` used to look for the file path from an incomplete file tree (only files from props), when it should look for it from the files from props **and** the files introduced by the default template, which is the output of `combineTemplateFilesToSetup`. Unfortunately, this was a mistake from the last breaking change, but easy to fix. 
Thanks @jerrywu001 for reporting it 🙌 
Closes #664
Closes #663

fix(getSandpackStateFromProps): get activeFile from files from props + template files

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx
sandpack-react/src/contexts/sandpackContext.test.tsx
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/utils/sandpackUtils.ts

Alternative to https://github.com/codesandbox/sandpack/pull/659
TLDR: When deleteFile is called, if there are no visibleFiles then open the entryFile. Also set the activeFile is the currently activeFile is deleted.
This change prevents sandpack from erroring out in the scenario where there a no "active files" in view, which results in "code" being undefined among other things.
Currently if you delete the last remaining active file, the whole page crashes.
New behaviour, the page doesn't crash and you receive a relevant error inside of the sandbox. This seems correct. Seen below (Deleted app.ts from the react.ts template). 
This automatically opens the entry file and presents an error related to user code.
1. Create a local sandpack
2. Use the deleteFile from context on the active file
3. …

fix(sandpack-react): prevent crash upon deleting last visible file

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx

The show highlight inline error feature didn't use to consider multiple files, which led to an unexpected state where it highlighted the wrong module/file instead of only the one which triggered the error. Example:
Fortunately, the bundler provider the path of the file, and we can filter errors out on each show-error messages.
---
cc @gaearon

fix(highlight inline error): make sure it highlight the correct file

---

sandpack-react/src/Playground.stories.tsx
sandpack-react/src/components/Preview/index.tsx
sandpack-react/src/components/common/Layout.tsx
sandpack-react/src/components/common/Stack.tsx
sandpack-react/src/presets/Sandpack.tsx
sandpack-react/src/types.ts
website/docs/docs/getting-started/custom-ui.md
website/docs/src/scss/_code.scss

This introduces the ability to resize the columns and rows on `<Sandpack />` (preset component):
- Desktop only: which means that mobile or touch devices don't support resizing panels in order to keep the usability accessible as the drag handler is not visible for non-cursor pointers;
- Boundaries: columns and rows have a minimum of 25% size and a max of 75%;
Plus, this PR introduces other improvements which aim to solve some layout issues on small-screen devices (set min-height for standard components), and other things to reduce the bundle size. 
Todo
Preview: https://2075ed-6006.preview.csb.app/iframe.html?id=intro-playground--preset&args=&viewMode=story

feat(Sandpack-preset): split panel

---

sandpack-client/src/client.ts
sandpack-react/src/Playground.stories.tsx
sandpack-react/src/contexts/sandpackContext.tsx

This reverts https://github.com/codesandbox/sandpack/pull/407, which is used to prevent Firefox from adding a new page to the main browser history. However, it seems that it's blocking other users from accessing some browser APIs (see #686). 
Let's give it another try and keep an eye out if the issue is still happening on Firefox, I hope it doesn't. 
Fix #686

fix(iframe): set `src` attribute 

---

website/docs/src/scss/_code.scss

https://sandpack.codesandbox.io/docs/getting-started/install
`website/docs/src/scss/_code.scss`
```diff
+ .nestedSandpack > .sp-wrapper > .sp-layout .sp-stack {
+   width: inherit !important;
+ }
```
@danilowoz

fix: website docs sandpack wrapper style

---

sandpack-react/src/components/CodeEditor/utils.ts
sandpack-react/src/components/FileExplorer/Directory.tsx
sandpack-react/src/components/common/Layout.tsx
sandpack-react/src/contexts/sandpackContext.test.tsx
sandpack-react/src/hooks/useSandpackClient.ts

```jsx
<SandpackProvider template="react">
<SandpackLayout>
<SandpackFileExplorer />
<SandpackCodeEditor closableTabs  />
<SandpackPreview />
</SandpackLayout>
</SandpackProvider>
```
`sandpack-react/src/components/common/Layout.tsx`
```diff
[`> .${THEME_PREFIX}-file-explorer`]: {
flex: 0.2,
minWidth: 200,
+    "@media screen and (max-width: 768px)": {
+      "&": {
+       minWidth: "100% !important",
+     },
+   },
},
```

fix: file explorer style in mobile

---

sandpack-react/src/templates/node/vite-react.ts

I implemented automatic runtime for VITE-REACT template.
<details>
<summary> 🤯🤯🤯 </summary>
This is magic, it works in the browser
</details>

fix(react-vite template): use automatic runtime for jsx

---

sandpack-react/src/components/Console/Console.stories.tsx
sandpack-react/src/components/Console/SandpackConsole.tsx
sandpack-react/src/components/Console/useSandpackConsole.ts
sandpack-react/src/hooks/useSandpackShellStdout.ts
website/docs/src/pages/advanced-usage/components.mdx

Closes https://github.com/codesandbox/sandpack/issues/692
Closes https://github.com/codesandbox/sandpack/issues/730

fix(console): improvements

---

sandpack-client/package.json

move `console-feed` to dev deps to fix warnings about peer dependencies, like this:
`warning "@codesandbox/sandpack-client > console-feed > linkifyjs@2.1.9" has unmet peer dependency "jquery@>= 1.11.0".`
This is safe because `console-feed` is bundled into a string, so end users don't need to install it
To test install `@codesandbox/sandpack-client` with `yarn`

fix(sandpack-client): move console-feed to dev deps

---

sandpack-react/babel.config.js
sandpack-react/rollup.config.js
sandpack-react/tsconfig.json

Enable `jsx-runtime` for `sandpack-react` package

fix(sandpack-react): use automatic runtime for jsx

---

sandpack-react/rollup.config.js
sandpack-react/src/components/Tests/Header.tsx
sandpack-react/src/components/Tests/SandpackTests.tsx
sandpack-react/src/components/Tests/Specs.tsx
sandpack-react/src/components/Tests/Summary.tsx
sandpack-react/src/components/Tests/Tests.stories.tsx
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/types.ts
website/docs/src/pages/advanced-usage/components.mdx

This pull request introduces a new feature to `SandpackProvider` options. 
Specifically, it adds the ability to hide test files and suppress their output from being logged to the console when a test fails. 
Additionally, it allows for the hiding of the `verbose` and `watch` buttons from the test console and prevents opening test files with test links from the console.
Currently, there is no option to hide test files or suppress their output when they fail in the `SandpackProvider` options. And, there is no option to hide the `verbose` or `watch` buttons from the tests console. 
Also when the user clicks on the test file path, even if it is hidden, the editor will open the test file.
With this feature, a `hideTestsAndSupressLogs` option is added to the `SandpackProvider` options. 
When set …

fix(sandpack-tests): introduce `hideTestsAndSupressLogs` prop

---

sandpack-react/src/presets/Sandpack.stories.tsx
sandpack-react/src/presets/Sandpack.tsx
sandpack-react/src/types.ts
website/docs/src/pages/getting-started/layout.mdx

feature: add rtl option (so easy to rtl layout)
- usage
```jsx
export const RtlLayout: React.FC = () => {
return (
<>
<Sandpack
options={{
rtl: true,
}}
template="react"
/>
</>
);
};
```

fix: add rtl layout option

---

sandpack-react/src/styles/index.ts

Fix https://github.com/codesandbox/sandpack/pull/787#issuecomment-1452251178

fix(getNodeProcess): check if process is available

---

sandpack-react/src/utils/stringUtils.ts

Discovered a small issue with keys when spamming the console with logs
`generateRandomId` is a bit too optimistic on how random Math.random is and is used as a unique value instead of a random value
`generateRandomId` has a counter to guarantee uniqueness across the entire application

fix: Make generateRandomId actually generate a unique id

---

sandpack-react/src/components/Console/ConsoleList.tsx
sandpack-react/src/components/Console/SandpackConsole.tsx
sandpack-react/src/components/ReactDevTools/index.tsx
sandpack-react/src/components/common/ErrorOverlay.tsx
sandpack-react/src/components/common/LoadingOverlay.tsx
sandpack-react/src/hooks/index.ts
sandpack-react/src/hooks/usePreviewProgress.ts
sandpack-react/src/hooks/useSandpackPreviewProgress.ts

reduce the number of circular dependencies
```
(!) Circular dependencies
src/index.ts -> src/components/index.ts -> src/components/FileExplorer/index.tsx -> src/components/common/index.ts -> src/components/common/ErrorOverlay.tsx -> src/index.ts
src/index.ts -> src/components/index.ts -> src/components/FileExplorer/index.tsx -> src/components/common/index.ts -> src/components/common/LoadingOverlay.tsx -> src/index.ts
src/index.ts -> src/components/index.ts -> src/components/FileExplorer/index.tsx -> src/components/common/index.ts -> src/components/common/LoadingOverlay.tsx -> src/hooks/usePreviewProgress.ts -> src/index.ts
...and 4 more
```
```
(!) Circular dependency
src/components/FileExplorer/ModuleList.tsx -> src/components/FileExplorer/Directory.tsx -> …
```

fix(sandpack-react): tweak imports to avoid circular deps

---

.gitignore
examples/nextjs/pages/index.tsx
examples/nextjs/tsconfig.json
examples/vite-react/App.jsx
examples/vite-react/index.html
examples/vite-react/index.jsx
examples/vite-react/package.json
examples/vite-react/vite.config.js
sandpack-react/package.json
sandpack-react/rollup.config.js
sandpack-react/scripts/rollup-remove-css-transformer.js
sandpack-react/src/styles/index.ts
sandpack-react/tsconfig.json
website/docs/src/pages/getting-started/layout.mdx
yarn.lock

We used try to remove the `typeof process` condition for default styles, but it bring a new issue for vite and a new PR https://github.com/codesandbox/sandpack/pull/795 add the condition back.
We need to understand that this kind of assert will always be `undefinde` for most of bundlers, vite/webpack etc, because there is no `process` in browser and all of them chose to directly replace `process.env.xxx` to the specify value, this means:
```js
const a = process.env.xxx // source code
// after compile
const a = true // the value you specified on config
```
So without remove the `typeof process` condition the _disable default style_ feature will never work on production (for some reason most of bundler actually provide a `process` object on dev mode).
It's not recommeded for client module …

fix: add new build for styleless

---

sandpack-react/src/components/Console/Console.stories.tsx
sandpack-react/src/components/Console/useSandpackConsole.ts
sandpack-react/src/hooks/useSandpackShellStdout.ts

This fixes a bug with the `Console` component where the `maxMessageCount` option isn't respected.
The `maxMessageCount` option is ignored and instead the default `MAX_MESSAGE_COUNT` value is used when determining if old logs should be cleaned up.
https://github.com/codesandbox/sandpack/issues/865
The `maxMessageCount` is respected so that logs are cleaned up based on what the user specifies.
1. Rendered an `Editor` and `Console` component
2. Changed the `maxMessageCount` option
3. Tested with the `vanilla` (client) and `node` (server) templates by logging more lines than the `maxMessageCount` option
4. Verified that the logs earlier in the list were cleaned up

fix(SandpackConsole): clear logs based on maxMessageCount option

---

sandpack-react/src/components/Preview/index.tsx
website/docs/src/pages/advanced-usage/components.mdx

Documentation both in the docs and in the TS definitions.
Closes: https://github.com/codesandbox/sandpack/issues/853

docs(showSandpackErrorOverlay): flag is missing docs (#853)

---

.codesandbox/ci.json
sandpack-react/src/Playground.stories.tsx
sandpack-react/src/contexts/utils/useClient.ts

If Sandpack tries to run `runSandpack` multiple times for the same cliend-id, it should first destroy the current instance and recreate the client again in order to wire up all listeners once again.
Closes https://github.com/codesandbox/sandpack/issues/852

fix(sandpack-content): destroy current client in case it tries to run it again

---

sandpack-client/src/clients/node/client.utils.ts
sandpack-client/src/clients/node/index.ts
sandpack-client/src/clients/node/inject-scripts/consoleHook.ts
sandpack-client/src/clients/node/inject-scripts/historyListener.ts
sandpack-client/src/clients/node/inject-scripts/index.ts
sandpack-react/src/components/Console/SandpackConsole.tsx
sandpack-react/src/components/Navigator/index.tsx
sandpack-react/src/components/Preview/Preview.stories.tsx
sandpack-react/src/components/Preview/index.tsx
sandpack-react/src/components/common/DependenciesProgress.tsx
sandpack-react/src/components/common/LoadingOverlay.tsx
sandpack-react/src/contexts/utils/useClient.ts
sandpack-react/src/hooks/useSandpackClient.ts
sandpack-react/src/hooks/useSandpackPreviewProgress.ts
sandpack-react/src/types.ts
website/docs/src/pages/advanced-usage/components.mdx

I'm trying to render two _Preview_ components that point to different pages (e.g. `/about` and `/careers`). This PR includes some rough changes and a Storybook story to better explain my intentions.
The core change is to add a `startRoute` prop to the Preview component that overrides the `startRoute` option that's passed to the Provider. When `createClient` is called in the `useClient` hook, the override value is used instead.
This idea could probably be extended for other things that may need an override, but for now, I explicitly exposed the `startRoute` functionality.
This _may_ be an unnecessary change.
Based on the [Preview Component documentation](https://sandpack.codesandbox.io/docs/advanced-usage/components#preview):
> There's nothing stopping you from rendering multiple previews …

feat(Preview): add startRoute prop to override Provider default

---

package.json
sandpack-client/package.json

This PR involves a change to the `sandpack-react` Storybook dev process.
Currently when you're working on the `sandpack-react` package via Storybook, there isn't an easy way for changes to the `sandpack-client` to be reflected immediately. You have to manually rebuild the `sandpack-client` on each change.
When spinning up the `sandpack-react` Storybook dev environment, we start the `sandpack-client` build process in watch mode. This allows changes in the client to automatically be reflected during development in Storybook. This seems to be [how Turborepo recommends it to be done](https://turbo.build/repo/docs/handbook/publishing-packages/bundling#setting-up-a-dev-script).
1. Clean up the `sandpack-client` dist files
2. Run `yarn react:dev`
3. Make a change to the `sandpack-client` …

chore(package.json): Build client in watch mode during react dev

---

sandpack-react/src/components/CodeEditor/index.tsx

This change adds a `className` prop to the `SandpackCodeEditor` component that gets merged with the root `SandpackStack` classes. The motivation behind this change is that I'd like to style the editor using tailwind, which isn't possible with the current setup. The change is similar to the existing implementation in the [SandpackPreview component](https://github.com/codesandbox/sandpack/blob/main/sandpack-react/src/components/Preview/index.tsx#L158).
The only way to style a `SandpackCodeEditor` component currently is to use the `style` prop.
A new `className` prop has been added to the `SandpackCodeEditor` component to make it possible to style the editor using class names.
I added the `className` prop to a few stories in Storybook and was able to see that the `classes` were applied to …

fix(SandpackCodeEditor): add className prop

---

sandpack-client/src/clients/static/index.ts

https://github.com/codesandbox/sandpack/issues/897
This looks like it made its way in as part of https://github.com/codesandbox/sandpack/pull/884. I'm a bit confused about how things were ever working though. Based on the change in this PR, it seems like things should have always been failing because `content` would have been converted to a string _and_ that if statement would have always been true because the Regex was wrong (i.e. missing the `.*`).
Sorry for not catching this on the first go around though. Hopefully, things should be good with this fix.
The `Uint8Array` content array is converted to a string in the Static template rather than being decoded.
The content is now properly decoded.
I just tried things in Storybook. I was able to reproduce the issue before making the change …

fix(Static Template): fix doctype injection

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx

[LanguageTool](https://languagetool.org/) is an extension for web browsers to fix grammatical issues like [Grammarly](https://www.grammarly.com/). 
However, the extension shows errors in Sandpacks's editor that is not intended for codes.
Disable the LanguageTool extension for code editor with `data-lt-active="false"` attribute.

fix(sandpack-react): disable LanguageTool extention for code editor

---

sandpack-client/src/clients/static/index.ts
sandpack-react/src/contexts/utils/useClient.ts
sandpack-react/src/presets/CustomSandpack.stories.tsx

A proposed solution for https://github.com/codesandbox/sandpack/issues/918. That bug is about how the `runSandpack` function doesn't work for the `static` template. While working through determining the root cause for that problem, I ran into a few other problems around how we register bundlers.
When we register a bundler it's only put into the `preregisteredIframes` object if the `useClient` status isn't `running`. The problem is that `runSandpack` only reruns clients that are in the `preregisteredIframes` object, which means if you register a client after things have started up, they won't get picked up by the `runSandpack` function.
When creating a `runtime` client, there's a [global listener that calls updateSandbox](https://github.com/codesandbox/sandpack/blob/main/sandpack-client/src …

fix(useClient): track all clients and update clients on runSandpack

---

sandpack-client/src/clients/runtime/index.ts
sandpack-client/src/clients/runtime/types.ts
sandpack-client/src/types.ts
sandpack-react/src/contexts/utils/useClient.ts
sandpack-react/src/types.ts

This should allow us to use sandpack at codesandbox with all the caching features we currently use

feat: add sandbox-id prop to compile

---

sandpack-react/src/components/ReactDevTools/index.tsx
sandpack-react/src/hooks/useSandpackTheme.ts
sandpack-react/src/styles/themeContext.tsx
website/docs/src/components/Themes.jsx

This improves the system color scheme support by listening to system color changes, and setting a preferrable color scheme to the sandpack theme context. Plus, it improves the documentation by mentioning that "auto" value will reflects the system color scheme, which can be the default values (light or dark)

feat: improve system color scheme support and documentation

---

sandpack-client/src/clients/runtime/index.ts
sandpack-client/src/clients/static/index.ts

Add the `sandbox="allow-downloads"` attribute to iframes. See https://github.com/codesandbox/codesandbox-client/pull/8253 for more context.
I'm not 100% sure whether this is the right fix, however:
- In production, the iframe on https://codesandbox.io/p/sandbox/allow-downloads-repro-py27jv contains the `allow="accelerometer; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; clipboard-write;"` attribute.
- The string `clipboard-write` is nowhere to be found in the `codesandbox-client` repo. But the value of the attribute literally matches how sandpack sets it.
- Does it mean sandpack is actually used in production to power sandboxes, therefore adding `allow-downloads` here will fix the regression for preview sandboxes? 🤔
No `allow-downloads` …

fix: add `allow-downloads` to iframes

---

sandpack-react/src/components/CodeEditor/CodeMirror.tsx
sandpack-react/src/presets/CustomSandpack.stories.tsx

Updates CodeMirror View constructor's useEffect's dependencies to make sure when `autoReload` option is changed we have re-evaluated `onCodeUpdate` version.
When we have a custom editors setup just like the examples shown in Doc > Quickstart > Multiple Editors, `autoReload` update doesn't work out because CodeMirror View doesn't re-evaluate `onCodeUpdate` so that we can't send the latest value of `shouldUpdatePreview`.
`onCodeUpdate` callback will be re-evaluated once `autoReload` option is changed.
Created a Story to test out everything works as expected.

fix: Update CodeMirror View when autoReload changed

---

sandpack-react/src/styles/themeContext.tsx
sandpack-react/src/themes/Theme.stories.tsx

Fixes a regression where themes are not updated on change. 
Closes: #1080 
Themes don't change when the theme prop is updated 
Themes now change as expected
- `yarn dev:react`
-`open http://localhost:6006/?path=/story/presets-themes--theme-switcher`
- Toggle select box
- Works ✅

fix: Theme state logic to account for non-prefers-color-scheme usage

---

sandpack-client/src/clients/node/index.ts

Bug fix
SandpackNode initializing with string selector ifame.parentNode will always be null, resulting in initialization failure
Fixed
1.  Invoke loadSandpackClient with string selector
2. Ensure normal loading with no errors

fix: Fixed sandpackNode initializing failure

---

sandpack-react/src/components/CodeEditor/CodeMirror.stories.tsx
sandpack-react/src/components/CodeEditor/CodeMirror.tsx

Closes: #1124 
This PR separates codemirror instantiation logic from subsequent prop updates. 
Previously every time a decorator or other dependency is updated, it would trigger a complete recreation of the sandpack instance, resulting in strange behaviour such as the cursor would be repositioned or elements would flash.
To fix this, I've moved all extension configuration into a seperate hook, when rerun will recreate the entire config and dispatch a codemirror `reconfigure` message which safely updates the instance without any side effects. 
I have added a storybook example which illustrates the behaviour.

fix: dynamically reconfigure codemirror instead of recreate on rerender

---

sandpack-react/src/contexts/utils/useFiles.test.ts
sandpack-react/src/contexts/utils/useFiles.ts

It prevents the code editor from overriding metadata information inside of a file, like readOnly, hidden, or any other custom data provided
The current behavior overrides the contents of the file with only the `{ code }` value, when the `updateFile` function is called using a string only, this is then also used by the code editor internally. I had made an issue here https://github.com/codesandbox/sandpack/issues/1084
It keeps the metadata of a file intact
I wasn't able to get the local environment running as i was getting errors during installation and execution, the lack of instructions on how to get the local environment running didn't allow me to test further
Some tests in the `useFiles.test.ts` or related might be failing as they check for the exact `{ code: value }`, but i feel like …

Keep the metadata of a file when updating the code

---

website/docs/src/pages/advanced-usage/components.mdx
website/docs/src/pages/advanced-usage/index.mdx

Documentation Update
Right now the docs say the SandpackLayout component accepts the theme prop which is incorrect and the link following it also is invalid.
[1132](https://github.com/codesandbox/sandpack/issues/1132#issuecomment-2094105867)
Now the docs is updated. SandpackLayout is changed to SandpackProvider and and link also points to a proper page showing the example.

fix(docs): Change Layout to Provider for accepting theme prop

---

website/landing/website.config.json

Changed react website link to the new domain.
Landing page link update.
It was using the legacy domain; which is reactjs.org
I changed it to react.dev.
No tests required. I just changed the URL in website's config.

landing: change react website link

---

sandpack-react/src/components/common/OpenInCodeSandboxButton/UnstyledOpenInCodeSandboxButton.tsx
sandpack-react/src/contexts/sandpackContext.tsx
sandpack-react/src/contexts/utils/useAppState.ts
sandpack-react/src/types.ts
website/docs/src/pages/getting-started/private-packages.mdx

feat(export): support private sandboxes in workspace

---

sandpack-react/src/PrivatePackage.stories.tsx
sandpack-react/src/components/common/OpenInCodeSandboxButton/UnstyledOpenInCodeSandboxButton.tsx
sandpack-react/src/contexts/utils/useFiles.test.ts
sandpack-react/src/contexts/utils/useFiles.ts

Plus, this publishs a new bundler version

fix(openCSB): pass children to buttons

---

sandpack-client/src/clients/runtime/types.ts
sandpack-react/src/Playground.stories.tsx
sandpack-react/src/hooks/useSandpackPreviewProgress.ts

Depends on https://github.com/codesandbox/codesandbox-client/pull/8471
https://github.com/codesandbox/sandpack/assets/4838076/c1963564-669b-40c0-8a0d-847c89321269

feat(loading): show dependency download progress

---

sandpack-client/src/clients/runtime/index.ts
sandpack-react/src/presets/CustomSandpack.stories.tsx

fix(sw): assign new channel port on reload

---

sandpack-client/src/clients/runtime/index.ts
sandpack-client/src/clients/runtime/types.ts
sandpack-client/src/types.ts
sandpack-react/src/Playground.stories.tsx
sandpack-react/src/PrivatePackage.stories.tsx
sandpack-react/src/contexts/utils/useClient.ts
sandpack-react/src/presets/Sandpack.tsx
sandpack-react/src/types.ts
sandpack-react/src/utils/useAsyncSandpackId.ts
website/docs/src/pages/advanced-usage/serving-static-files.mdx

When using Private Package, Sandpack needs a deterministic bundler URL to persist the authentication token in the cookies. Clearly, this is not compatible with how SW works because it needs unique URLs by sandbox. 
So, this implements a new feature to generate a deterministic short id based on the `useId` React hook (DOM location-based and probably more), and an SHA generated by files. I believe this should be okay to avoid conflicts between sandboxes.

fix(client): use stable sw id

---

sandpack-react/src/components/CodeEditor/CodeMirror.stories.tsx
sandpack-react/src/components/CodeEditor/CodeMirror.tsx

Closes https://github.com/codesandbox/sandpack/issues/1185

fix(read only): use codemirror instance with decorators

---

website/docs/src/pages/advanced-usage/components.mdx

The options table for SandpackTests in the documentation has been modified as it was not displaying correctly.
You can check it here: https://sandpack.codesandbox.io/docs/advanced-usage/components#tests
|AS-IS|TO-BE|
|---|---|
|<img width="796" alt="image" src="https://github.com/user-attachments/assets/e0655ddc-7e39-4878-a2ed-b9ccb0b2cedf">|<img width="794" alt="image" src="https://github.com/user-attachments/assets/03a7783b-3e88-45fe-9f8c-bf8c43a4eb8d">|

docs: fix SandpackTests options table display

---

sandpack-react/src/components/Tests/FormattedError.tsx

close https://github.com/codesandbox/sandpack/issues/1113
The SandpackTests component was crashing when throwing a string instead of an Error instance.
The problem occurred because `error.message` was `undefined`, causing the escapeHtml function to fail when attempting to replace.
Implemented nullish handling to safely process cases where error.message is undefined.
https://github.com/user-attachments/assets/ce317d3e-223a-42fc-ab1e-c641bed7fa0a
https://github.com/user-attachments/assets/4f1a9f27-9fd2-4044-b99f-32c44e0fd1c9

fix: handle string errors in SandpackTests component

---

sandpack-react/src/components/Console/utils/transformers.ts

**Issue:**
Sandpack currently uses `eval` to obtain the global object, which triggers CSP `unsafe-eval` violations. This poses security risks and limits the ability to use Sandpack in environments with strict CSP policies.
**Solution:**
Replaced the `eval`-based approach with an IIFE that sequentially checks for `globalThis`, `self`, `window`, and `global` to securely access the global object without violating CSP policies.
**Testing:**
Tested in a local development environment with CSP enforced to ensure no violations occur.
**Related Issue:**
https://github.com/codesandbox/sandpack/issues/1221

fix: replace eval with globalThis to comply with CSP policies

---

website/landing/components/Hero/HeroDesktop/HeroDesktop.tsx

In file `website/landing/components/Hero/HeroDesktop/HeroDesktop.tsx`, isMounted always return true
```js
const isMountedRef = useRef(false);
...
<AnimatedBox
ref={sectionRef}
css={{ height: "200vh" }}
id="container"
style={
{
"--progress": isMounted ? progress : 0,
"--opacity": isMounted ? opacity : 1,
"--progress-inverse": isMounted ? progressInverse : 1,
"--rotate": isMounted ? rotate : -90,
"--scale": isMounted ? scale : 2.08,
"--container-scale": isMounted ? containerScale : 1,
"--sandpack-preview-opacity": isMounted ? sandpackPreviewOpacity : 0,
// eslint-disable-next-line @typescript-eslint/no-explicit-any
} as any
}
>
```

fix(landing): invalid isMounted judgment
